### ISSUE TITLE
install bower

### ISSUE THREAD

**Issue by MySchizoBuddy** [FrissAnalytics/shinyJsTutorials#1]
bower has to be installed separately. bower requires node to be installed. The article should mention that.
Also Rstudio allows you to create an R package via it's "New Project" dialog box. Is that the same as using devtools::create("C3").

**Comment by erwinschuijtvlotfriss** [comment]
We did the steps of installing bower quite a while ago and we missed it when creating the tutorials.
We will update the tutorial to either include the installation or get rid of the dependency of bower altogether.

Yes using the "New Project" dialog is equivalent to devtools::create("")

**Comment by MySchizoBuddy** [comment]
for me it actually gave an error that bower is not found. I then installed bower separately.

**Comment by FrissAnalytics** [comment]
we decided its best to remove the bower reference completely. Even though it is a nice feature, you do have to install node.js and bower, and still edit a yaml file by hand. We'll likely include a dist folder which will hold all the relevant files you need and refer to that. We may add a side note on the use of bower.

Thanks for bringing this issue up, we expect to have an updated version of the tutorial somewhere today or tomorrow.

**Comment by MySchizoBuddy** [comment]
for me it actually gave an error that bower is not found. I then installed bower separately.

**Comment by FrissAnalytics** [comment]
fyi: the tutorial on the RSTUDIO website has been updated. If anything is still unclear let us know!
