### ISSUE TITLE
tutorial is gone from Rstudio website?

### ISSUE THREAD

**Issue by ding0066** [FrissAnalytics/shinyJsTutorials#12]
Hi,

I am a big fan of this tutorial series and curious if anyone knew why the tutorial series have been taken down from Rstudio websites.

Thanks,
Derek

**Comment by mine-cetinkaya-rundel** [comment]
Hello - the content has not been taken down, but it has been moved to the articles section (see http://shiny.rstudio.com/articles/#extensions). The content of these tutorials are quite a bit more advanced compared to our other Get Started material. Hence the articles section, which houses more advanced content, seemed like a better fit. Glad to hear that the content of the Shiny/JS tutorials has been useful!

**Comment by ding0066** [comment]
Thanks! Glad to know it is still there! All the best!
