### ISSUE TITLE
how C3Guage.R and C3Guage.js work together

### ISSUE THREAD

**Issue by MySchizoBuddy** [FrissAnalytics/shinyJsTutorials#2]
please elaborate on how C3Guage.R and C3Guage.js work together. Looks to me all the communication is happening behind the scene.

**Comment by FrissAnalytics** [comment]
to answer your question more precisely requires to go into the internals of HTMLWidgets, which we consider out of scope for this tutorial. 

What is most important to realize is that in C3Gauge.R we set the R data and options and put these in a list called `x`. Remember, `x` is an R object. Via a call to htmlwidgets::createWidget, HTMLWidgets will pass this information to javascript in which the R object is translated into something javascript understands, which is where jsonlite comes in. 

This indeed happens behind the scenes. As we point out in the tutorial the step from R data to javascript data is often the most difficult step. 

A simple thing you can do is to write

``` javascript
console.log(x);
```

inside the `renderValue` function in the javascript code so you can see what object is actually created at the javascript side, after it is passed from R.
