### ISSUE TITLE
barchart library

### ISSUE THREAD

**Issue by daroczig** [FrissAnalytics/shinyJsTutorials#4]
First of all, thanks for this fantastic resource and tutorial -- your hard work on this is highly appreciated and looking forward to the next articles.

A quick question though: did you already publish the widget or demo Shiny app with source code generating the stacked bar chart below the gauges?

**Comment by FrissAnalytics** [comment]
thanks for the kind words! at this stage we did not yet release that part of the code base. However, I can send you some code for that particular chart if you want (or a variation on this chart). What precisely do you have in mind? FYI, we will cover this chart (and others) in depth in the next tutorial, which should be out within a few weeks. In addition to what you have seen you then can also send updates to an already initialized chart via a proxy object e.g. changing the selected x or y range, removing series, adding series, or changing e.g. to a stacked bar chart.

**Comment by daroczig** [comment]
Thank you very much for your prompt and kind reply, Herman!

If you can share the related code in a gist or e-mail, that would be very helpful. Although I look forward to the detailed tutorial, now I try to replicate the below barchart -- which includes the overall counts on the left _y_ axis as bar charts and the group percentages on the right _y_ axis with lines:

![image](https://cloud.githubusercontent.com/assets/495736/15270508/42bf07dc-19d7-11e6-9230-9893f1b3a4a5.png)

**Comment by FrissAnalytics** [comment]
Hi,
I'll put something together for you and send you an update tomorrow, ok?
best H

**Comment by daroczig** [comment]
That would be very cool, thank you very much!

**Comment by FrissAnalytics** [comment]
Hi,

I just provided you access to a private GITHUB repo that contains a small app I made for you demonstrating the c3.js line/bar example, including the brush.

best H

**Comment by daroczig** [comment]
Thank you very much, I've just cloned the repo and found the sources extremely useful & self-explanatory -- your kind and extremely quick help are highly appreciated!
