### ISSUE TITLE
C3Gauge R File

### ISSUE THREAD

**Issue by muelleRw** [FrissAnalytics/shinyJsTutorials#5]
On the tutorial, the last block of code for C3Gauge.R has package = 'C3Gauge'.
This should be package = 'C3'.

**Comment by FrissAnalytics** [comment]
Hi,
you're absolutely correct. We'll update the tutorial accordingly!
kind regards, Herman

**Comment by FrissAnalytics** [comment]
the tutorial has been updated. Thanks for informing us!
