### ISSUE TITLE
Invitation to the satRday conference @ Budapest 2016

### ISSUE THREAD

**Issue by daroczig** [FrissAnalytics/shinyJsTutorials#7]
Hello Herman,

sorry to bother you here -- I tried to reach you on LinkedIn as well, but unfortunately, without any success.

To keep it short, we are organizing the first satRday conference around the world, which will happen to be at Budapest, Hungary in this September -- and it would be great to have you there: http://budapest.satrdays.org/#cfp

I would love to see a 1.5 hrs long workshop on Shiny from you, but of course, it would be great to hear a regular talk on your R related projects at Friss Analytics too.

Please let me know if you are interested at my gergely@satrdays.org or daroczig@rapporter.net e-mail address, and of course, feel free to close/delete this issue.

Thanks,
Gergely

**Comment by FrissAnalytics** [comment]
I'm happy to be there if I can find appropriate funds to travel, as discussed in a private email.
