### ISSUE TITLE
Incorrect reference to package name

### ISSUE THREAD

**Issue by CarlesCG** [FrissAnalytics/shinyJsTutorials#9]
The foo `addIntroJS ` at the file `shinyJsTutorials/tutorials/materials4/FrissIntroJSBasic/R/FrissIntroJS.R` should reference to:  
 
`package='FrissIntroJSBasic')` instead of   
`package='FrissIntroJS')`

The name of the package install from `shinyJsTutorials/tutorials/materials4/FrissIntroJSBasic` contains the suffix `*Basic.` So either change the name of the package or the reference. 

Great tutorial!

**Comment by FrissAnalytics** [comment]
thanks! I updated the addResourcePath reference in the GITHUB repo. Good to hear you like the tutorials :-)
